### ISSUE TITLE
      this.delete(passDirectory, passFile);

### ISSUE THREAD

**Issue by nicowernli** [alexeynobody/pass-flutter#10]
I'm getting this error after `ZipDecoder().decodeBytes(passArchive)`. I tried with several pkpasses of different companies and get the same error every time. 

I'm testing it on Android, should the plugin work on Android too?

**Comment by alexey-nobody** [comment]
Yes, it work on Android. Please attach a file, I'll see why it throw error

**Comment by nicowernli** [comment]
Here is a link to the file.

https://drive.google.com/file/d/1tOrpTBTZxH6zbdzjRpMGyY7ZRe3pQE6J/view?usp=sharing

**Comment by alexey-nobody** [comment]
> Here is a link to the file.
> 
> https://drive.google.com/file/d/1tOrpTBTZxH6zbdzjRpMGyY7ZRe3pQE6J/view?usp=sharing

No access for me

**Comment by nicowernli** [comment]
Sorry about that, you have access now

**Comment by alexey-nobody** [comment]
I checked this file, everything is fine. Can I have a code example, how to reproduce the error?

**Comment by nicowernli** [comment]
This afternoon CET I'll upload the code that is failing for me. Thanks for all the help

**Comment by nicowernli** [comment]
Hi sorry for the late update, this is the code I'm running right now.
I also tried using a local file url but didn't work neither: `file:///Users/nicowernli/Downloads/3FB5RNHDOJHELADJLCBJIN.pkpass`

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pass_flutter/pass_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    return MaterialApp(
      title: 'NWALLET',
      home: Scaffold(
        body: FutureBuilder(
          future: Pass().saveFromUrl(
              url:
                  "https://drive.google.com/file/d/11XdNlIv1mvXkOX4jDTOJiIkxOT0h5EXy/view?usp=sharing"),
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(
                child: Text(
                  snapshot.error.toString(),
                  style: TextStyle(color: Colors.red),
                ),
              );
            } else {
              return Center(
                child: Text('Success!'),
              );
            }
          },
        ),
      ),
    );
  }
}
```

**Comment by nicowernli** [comment]
The problem comes from the `_findSignature` method of the `archive-2.0.13/lib/src/zip/zip_directory.dart` file. I know that's an external library but maybe helps to find the issue

**Comment by alexey-nobody** [comment]
Sorry for the long answer, URL in the saveFromUrl method should lead to a direct download, but not on the cloud link. 


> I also tried using a local file url but didn't work neither: `file:///Users/nicowernli/Downloads/3FB5RNHDOJHELADJLCBJIN.pkpass`

This link from local files, not from phone?


I checked everything, is working fine. Change the link and it all works! )
