### ISSUE TITLE
_convertToColor null exception

### ISSUE THREAD

**Issue by srcnysf** [alexeynobody/pass-flutter#13]
in Some case when I generate Event pass from [https://www.passsource.com/](url)  the `labelColor` comes null so 

_convertToColor method throw excetion  

It can be solved by adding 

```
 static Color _convertToColor(String rgbCssColor) {
    if (rgbCssColor == null) {
      return Color.fromRGBO(255, 255, 255, 1);
    }
...
}
```

**Comment by srcnysf** [comment]
@alexeynobody I solve that on actual code at the moment but I will fork and open pr later today

**Comment by alexey-nobody** [comment]
Hello @srcnysf, thanks. I'm waiting for the pr and I will update the library immediately after viewing
