### ISSUE TITLE
pass.json escape \n \t \r

### ISSUE THREAD

**Issue by srcnysf** [alexeynobody/pass-flutter#14]
![image](https://user-images.githubusercontent.com/11577082/89403274-babb8c00-d720-11ea-82f4-e778db067631.png)

in some pass i am using comes with \n \t \r chars inside json. It needs some replace method to taka the actual json.

I have been researching and trying to solve the issue for couple days but I haven't solved it yet. @alexeynobody can you help me with this ?

**Comment by alexey-nobody** [comment]
Yes. You can send an example of such a pass?

**Comment by srcnysf** [comment]
you can try it by [http://owallet.com.tr/androidwalletdev_062020/demo/pass.php](url)

**Comment by srcnysf** [comment]
@alexeynobody any updates on this issue ?

**Comment by alexey-nobody** [comment]
@srcnysf It takes some time to research this bug

**Comment by srcnysf** [comment]
@alexeynobody ok I am on it too. If I find anything helpful I will let you know
