### ISSUE TITLE
_getImage returns always null

### ISSUE THREAD

**Issue by srcnysf** [alexeynobody/pass-flutter#17]
![image](https://user-images.githubusercontent.com/11577082/89473713-40285600-d78c-11ea-91bd-d38c1c3ab0d4.png)

Although the dile paths exist, `path.existsSync() ` return false so logo,backround etc always remains null.

**Comment by alexey-nobody** [comment]
@srcnysf You can send an example of such a pass?

**Comment by srcnysf** [comment]
@alexeynobody  https://www.passsource.com/pass/create.php?hashedSerialNumber=eNortjIysVLKiAyoCnTOCDHNTQnzDc8M8PIKz0tPt7VVsgZcMKTJCgI,&download=true

**Comment by alexey-nobody** [comment]
@srcnysf Thanks, I found the problem, I'll fix it today. One of the three images is missing.
