### ISSUE TITLE
Does not appear in Apple Wallet

### ISSUE THREAD

**Issue by faider29** [alexeynobody/pass-flutter#20]
Hello
In Xcode im added certificate to wallet.
When im take url to `.pkpass`, I use ```Pass().saveFromUrl```, and yes, pass saved to internal memory, but im thinking that's it must be added to Apple Wallet. 
Or I must do something more ?

Thanks

**Comment by Sarexer** [comment]
Same problem

**Comment by alexey-nobody** [comment]
@faider29 @Sarexer It doesn't work that you think, there are other tools for this. 🙂

**Comment by JakobStadlhuber** [comment]
> @faider29 @Sarexer It doesn't work that you think, there are other tools for this. 🙂

which other tools do you mean? I didn't find something

**Comment by alexey-nobody** [comment]
@JakobStadlhuber Unfortunately, I don't have this information. I do not plan to implement this feature in my library.
