### ISSUE TITLE
Color problems

### ISSUE THREAD

**Issue by eltiganiomar** [alexeynobody/pass-flutter#21]
Hello. I am using this package, and I managed to get pass from URL. Everything looks fine except the colors.
The passFile.pass.backgroundColor, the foregroundColor and the labelColor are all white(rgb(255, 255, 255)) but they should be colored. Can anyone help me please?

**Comment by alexey-nobody** [comment]
@mester900 You can send an example of such a pass?

**Comment by eltiganiomar** [comment]
Here is a url where the backgroundColor, foregroundColor and labelColor are colored:
https://pass.gymbase.hu/?domain=demo&key=GB-5E4519D56D498&code=LBPQ77

**Comment by eltiganiomar** [comment]
@alexeynobody  Have you found a solution for this problem?

**Comment by eltiganiomar** [comment]
I managed to solve the problem. There was some problem with the RegExp.

**Comment by alexey-nobody** [comment]
> I managed to solve the problem. There was some problem with the RegExp.

Hi, I was busy at work and I don't research this problem. If you found the solution, can you create PR for this and help me?

**Comment by eltiganiomar** [comment]
I made a PR, check it out if you have time.
