### ISSUE TITLE
Error compiling in AndroidStudio for iOS

### ISSUE THREAD

**Issue by GrupoDO** [alexeynobody/pass-flutter#25]
The last version is failing with the error "The plugin `pass_flutter` doesn't have a main class defined in /Users/fede/.pub-cache/hosted/pub.dartlang.org/pass_flutter-1.2.1/android/src/main/java/com/alexeynobody/pass_flutter/PassFlutterPlugin.java or /Users/fede/.pub-cache/hosted/pub.dartlang.org/pass_flutter-1.2.1/android/src/main/kotlin/com/alexeynobody/pass_flutter/PassFlutterPlugin.kt. This is likely to due to an incorrect `androidPackage: com.alexeynobody.pass_flutter` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile."

Please, tell me if you need more information about this error.

Thank you.

**Comment by alexey-nobody** [comment]
@GrupoDO I fixed this bug. In version 1.2.2 all it's ok- https://pub.dev/packages/pass_flutter/versions/1.2.2

**Comment by GrupoDO** [comment]
> 
> 
> @GrupoDO I fixed this bug. In version 1.2.2 all it's ok- https://pub.dev/packages/pass_flutter/versions/1.2.2

Now this works ok!. Thank you
