### ISSUE TITLE
labelColor and foregroundColor are optional fields for the pass json. But required by this library

### ISSUE THREAD

**Issue by vanomak** [alexeynobody/pass-flutter#32]
Killed couple of days by figuring this out

**Comment by SaudElabdullah** [comment]
Please some one answer or solve this issue. It is really driving me crazy.

**Comment by alexey-nobody** [comment]
@SaudElabdullah Hello. This issue resolved in 1.2.1 version. In model this fields are optional
<img width="363" alt="image" src="https://user-images.githubusercontent.com/12109503/149941143-463bc141-85d0-486c-af45-6a0929c14881.png">
Were we discussing another bug you can reopen this issue or make a pr with fix.
