### ISSUE TITLE
Crashing on iOS after fetching preview or saving

### ISSUE THREAD

**Issue by abdulahad1991** [alexeynobody/pass-flutter#35]
Could not cast value of type '__NSArrayM' (0x1f397f190) to 'FlutterStandardTypedData' (0x1f397f178).
2022-02-09 00:44:14.720718+0500 Runner Dev[2961:154000] Could not cast value of type '__NSArrayM' (0x1f397f190) to 'FlutterStandardTypedData' (0x1f397f178).
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001cd1ee7b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1cd1ee7b0 <+8>:  b.lo   0x1cd1ee7cc               ; <+36>
    0x1cd1ee7b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1cd1ee7b8 <+16>: mov    x29, sp
    0x1cd1ee7bc <+20>: bl     0x1cd1cb1fc               ; cerror_nocancel

**Comment by ShonFrazier** [comment]
Similar error for me: 

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
```

Safari can access the same URL for downloading the pass, displays the pass, and offers to add it to Wallet. The JSON must be valid or this wouldn't work. Full error with stack:

```
2022-02-15 14:05:36.088725-0500 Runner[12477:2139737] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      _$PassJsonFromJson (package:pass_flutter/src/models/pass_json/pass_json.g.dart:35:63)
#1      new PassJson.fromJson (package:pass_flutter/src/models/pass_json/pass_json.dart:49:7)
#2      PassParser._parsePassJson (package:pass_flutter/src/pass_parser.dart:29:21)
<asynchronous suspension>
#3      PassParser.parse (package:pass_flutter/src/pass_parser.dart:45:22)
<asynchronous suspension>
#4      fetchApplePass (package:<<redacting path>>/apple_passes.dart:35:23)
<asynchronous suspension>
```

**Comment by abdulahad1991** [comment]
Hi,

I managed to fix the issues.

It was due to permissions.

What you will have to do it add Wallet Capability from Xcode as well as
Checkmark the wallet feature from identifier from Apple Developer account

**Comment by ShonFrazier** [comment]
Although my error message is similar, my issue is actually different. I'll create a new issue and prepare a PR. 

Edit: created issue #36

**Comment by alexey-nobody** [comment]
Hi guys, I processed PR and released a new version. Reopen this issue, if the error is still here.
